FROM --platform=linux/amd64 ltdps/edxapp:m5-fixed AS node_runtime

FROM py36-p1b-studio-builder:r5 AS paver_runtime

FROM ltdps/edxapp:py36-r1-p1b-ora2-runtime-20260804-r3

COPY --from=node_runtime /edx/app/edxapp/nodeenvs/edxapp/bin/node /usr/local/bin/node
COPY --from=node_runtime /edx/app/edxapp/nodeenvs/edxapp/lib/node_modules /usr/local/lib/node_modules
COPY --from=node_runtime /lib/x86_64-linux-gnu /lib/x86_64-linux-gnu
COPY --from=node_runtime /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2
COPY --from=node_runtime /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu
COPY --from=paver_runtime /usr/local/bin/paver /usr/local/bin/paver
COPY --from=paver_runtime /usr/local/lib/python3.6/site-packages/Paver-1.3.4.dist-info /usr/local/lib/python3.6/site-packages/Paver-1.3.4.dist-info
COPY --from=paver_runtime /usr/local/lib/python3.6/site-packages/paver /usr/local/lib/python3.6/site-packages/paver
COPY --from=paver_runtime /usr/local/lib/python3.6/site-packages/argh /usr/local/lib/python3.6/site-packages/argh
COPY --from=paver_runtime /usr/local/lib/python3.6/site-packages/argh-0.26.2.dist-info /usr/local/lib/python3.6/site-packages/argh-0.26.2.dist-info
COPY --from=paver_runtime /usr/local/lib/python3.6/site-packages/pathtools /usr/local/lib/python3.6/site-packages/pathtools
COPY --from=paver_runtime /usr/local/lib/python3.6/site-packages/pathtools-0.1.2.dist-info /usr/local/lib/python3.6/site-packages/pathtools-0.1.2.dist-info
COPY --from=paver_runtime /usr/local/lib/python3.6/site-packages/watchdog /usr/local/lib/python3.6/site-packages/watchdog
COPY --from=paver_runtime /usr/local/lib/python3.6/site-packages/watchdog-2.3.1.dist-info /usr/local/lib/python3.6/site-packages/watchdog-2.3.1.dist-info
COPY --from=paver_runtime /usr/local/lib/python3.6/site-packages/wrapt /usr/local/lib/python3.6/site-packages/wrapt
COPY --from=paver_runtime /usr/local/lib/python3.6/site-packages/wrapt-1.16.0.dist-info /usr/local/lib/python3.6/site-packages/wrapt-1.16.0.dist-info
COPY --from=paver_runtime /usr/local/lib/python3.6/site-packages/sass.py /usr/local/lib/python3.6/site-packages/sass.py
COPY --from=paver_runtime /usr/local/lib/python3.6/site-packages/_sass.cpython-36m-aarch64-linux-gnu.so /usr/local/lib/python3.6/site-packages/_sass.cpython-36m-aarch64-linux-gnu.so
COPY --from=paver_runtime /usr/local/lib/python3.6/site-packages/libsass-0.10.0.dist-info /usr/local/lib/python3.6/site-packages/libsass-0.10.0.dist-info

RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm \
    && ln -s /usr/local/lib/node_modules/npm/bin/npx-cli.js /usr/local/bin/npx
